version: 0.2
phases:
  install:
    commands:
      - gem install jekyll  
  build:
    commands: 
      - echo "Building site"
      - JEKYLL_ENV=production jekyll build 
      - echo "Copying to S3"
      - aws s3 sync _site s3://$BUCKET_NAME
      - echo "Success"
