AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a CICD pipeline for the NED application
Parameters:
  BucketName:
    Description: ''
    NoEcho: false
    Type: String
  GithubBranch:
    Description: ''
    NoEcho: false
    Type: String
  GithubOwner:
    Description: ''
    NoEcho: false
    Type: String
  GithubRepo:
    Description: ''
    NoEcho: false
    Type: String
  GithubToken:
    Description: ''
    NoEcho: true
    Type: String
Resources:
  BuildArtifactsBucket:
    Properties:
      BucketName: !Sub '${AWS::StackName}-cicd-artifacts-bucket'
    Type: AWS::S3::Bucket
  CodeBuildProject:
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: !Sub '${BuildArtifactsBucket}/${AWS::StackName}-codebuild'
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: BUCKET_NAME
            Value: !Ref 'BucketName'
        Image: 'aws/codebuild/ruby:2.3.1' 
        Type: LINUX_CONTAINER
      Name: !Sub '${AWS::StackName}-build-jekyll-codebuild'
      ServiceRole: !GetAtt 'CodeBuildProjectRole.Arn'
      Source:
        Type: CODEPIPELINE
    Type: AWS::CodeBuild::Project
  CodeBuildProjectRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /managed/
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-build-jekyll-codebuild'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-build-jekyll-codebuild:*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-log-access-${AWS::StackName}'
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-s3-access-${AWS::StackName}'
      RoleName: !Sub '${AWS::StackName}-codebuild-build-jekyll-service-role'
    Type: AWS::IAM::Role
  CodePipelinePipeline:
    Properties:
      ArtifactStore:
        Location: !Ref 'BuildArtifactsBucket'
        Type: S3
      Name: !Sub '${AWS::StackName}-default-pipeline'
      RoleArn: !GetAtt 'CodePipelineServiceRole.Arn'
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Branch: !Ref 'GithubBranch'
                OAuthToken: !Ref 'GithubToken'
                Owner: !Ref 'GithubOwner'
                Repo: !Ref 'GithubRepo'
              Name: get-source
              OutputArtifacts:
                - Name: source-zip
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref 'CodeBuildProject'
              InputArtifacts:
                - Name: source-zip
              Name: codebuild
              OutputArtifacts:
                - Name: built-zip
              RunOrder: 1
          Name: Build
    Type: AWS::CodePipeline::Pipeline
  CodePipelineServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /managed/
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${BuildArtifactsBucket}'
                  - !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codepipeline-s3artifact-access-${AWS::StackName}-default'
        - PolicyDocument:
            Statement:
              - Action: iam:PassRole
                Effect: Allow
                Resource:
                  - !GetAtt 'CodeBuildProjectRole.Arn'
            Version: '2012-10-17'
          PolicyName: !Sub 'codepipeline-passrole-access-${AWS::StackName}-default'
        - PolicyDocument:
            Statement:
              - Action:
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:BatchGetBuilds
                Effect: Allow
                Resource:
                  - !GetAtt 'CodeBuildProject.Arn'
            Version: '2012-10-17'
          PolicyName: !Sub 'codepipeline-build-access-${AWS::StackName}-default'
      RoleName: !Sub 'codepipeline-service-role-${AWS::StackName}-default'
    Type: AWS::IAM::Role
